### ISSUE TITLE
What is your dock application?

### ISSUE THREAD

**Issue by lzbferrari** [varlesh/papirus-plasma-theme#1]
What is your dock application in this screenshot ?
http://kde-look.org/CONTENT/content-pre1/169977-1.png

**Comment by varlesh** [comment]
Hello. I can not add comments on KDE-Look, sorry ))
Dock - Plank:
```
sudo apt-get install plank```
or repository:
https://launchpad.net/~docky-core/+archive/ubuntu/stable
